name: Deploy Angular to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --configuration production

    - name: Create deployment package
      # This creates a compressed archive of the built files
      run: tar -czvf deploy.tar.gz -C dist/projet-quiz/browser .

    - name: Upload and Unpack on VM
      # This uses a single, reliable SSH session to deploy and set permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          # Use scp to copy the single archive file to a temporary location on the VM
          scp -o StrictHostKeyChecking=no deploy.tar.gz ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:/tmp/deploy.tar.gz

          # Unpack the archive into the webroot, overwriting old files
          sudo tar -xzvf /tmp/deploy.tar.gz -C /var/www/html/

          # Set the correct ownership and permissions
          sudo chown -R www-data:www-data /var/www/html

          # Clean up the uploaded archive from the temporary directory
          rm /tmp/deploy.tar.gz
