name: Deploy Angular to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --configuration production

    - name: Create deployment package
      run: |
        mkdir release
        cd dist/projet-quiz/browser
        tar -czvf ../../../release/deploy.tar.gz .

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          # Create a temporary directory for the new release
          mkdir -p /tmp/quizz-release

          # Upload the packaged release file
          # Note: This uses the ssh-action's built-in scp functionality
          scp -o StrictHostKeyChecking=no -r release/deploy.tar.gz ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:/tmp/quizz-release/

          # Unpack the release and set permissions
          cd /var/www/html
          sudo rm -rf ./*
          sudo tar -xzvf /tmp/quizz-release/deploy.tar.gz -C .
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html

          # Clean up the temporary release files
          rm -rf /tmp/quizz-release
